### ISSUE TITLE
The problem with the extra mesh on the head

### ISSUE THREAD

**Issue by AcTiViSioN911** [NxRoot/ALSV4-Metahumans#1]
Please download metahuman Io and look at her glasses, they will be in her hands and not on her head, and I couldn't fix it.

**Comment by alisahanyalcin** [comment]
![image](https://user-images.githubusercontent.com/34830846/230145240-776db944-ce0a-46b8-a358-ff692c2c7c37.png)

- click here
- select 
- drag and drop into the mesh
- rest the transform location and rotation

https://user-images.githubusercontent.com/34830846/230145110-39a75abb-45e5-4acd-a4a2-feeb38c8b666.mp4
