### ISSUE TITLE
Warning message when I add metahuman

### ISSUE THREAD

**Issue by AcTiViSioN911** [NxRoot/ALSV4-Metahumans#2]
```
There are some changes to the Common assets in this project. If you continue importing this MetaHuman, your local changes to the following assets may be overwritten.
Continue anyway?
MetaHumans/Common/Female/Medium/NormalWeight/Body/metahuman_base_skel.uasset
MetaHumans/Common/Female/Medium/NormalWeight/Body/MetaHuman_LODSettings.uasset
MetaHumans/Common/Female/Medium/NormalWeight/Body/f_med_nrw_body_Physics.uasset
```
Should I agree to a replacement or after applying, replace new files with old ones from the archive? If I refuse, then MH will not be added, so I'm wondering if these files are needed.

**Comment by AcTiViSioN911** [comment]
All animations are broken after replacement, so add a notice about it

**Comment by NxRoot** [comment]
> All animations are broken after replacement, so add a notice about it

I can't be responsible for problems that might occur when merging my project files with other projects.
This project is meant to be used as a starting base, therefore Im closing this issue.
