### ISSUE TITLE
Easy way to get this to work with UE 5.2 or 5.3?

### ISSUE THREAD

**Issue by Alfrediscool12** [NxRoot/ALSV4-Metahumans#7]
Is there any easy way to get this to work in 5.2 or 5.3?

**Comment by NxRoot** [comment]
Right click `.uproject` file inside the project folder --> Switch Engine Version --> Select 5.2/5.3.
Then open the project.
That doesn't work?

**Comment by NxRoot** [comment]
Closed due to inactivity.
